frontend.install now waits for web service to be ready.

diff --git a/tools/docker/scheduledb/frontend.install b/tools/docker/scheduledb/frontend.install
--- a/tools/docker/scheduledb/frontend.install
+++ b/tools/docker/scheduledb/frontend.install
@@ -22,12 +22,15 @@ msg INFO "Determine if we are running on Docker Toolbox or Linux ..."
 if [ ! -z "$DOCKER_MACHINE_NAME" ] ; then
     msg INFO "... We are running in Docker Toolbox ..."
     export TSSGAPIURL="http://$(docker-machine ip)"
+    export TSSGAPPURL="${TSSGAPIURL}:4200"
 elif [ "$(hostname)" == "Ubuntu-Studio-14" ] ; then
     msg INFO "... We are running in a Linux server ..."
     export TSSGAPIURL="http://backend.sdb.technologynursery.org"
+    export TSSGAPPURL="http://frontend.sdb.technologynursery.org"
 else
     msg INFO "... We are running in a local Linux ..."
     export TSSGAPIURL="http://localhost"
+    export TSSGAPPURL="${TSSGAPIURL}:4200"
 fi
 msg INFO "Set the appropriate value into src/environments/environment.ts ..."
 sed -ie "s,^\(^[[:space:]]*TSSGAPIURL: \).*$,\1\'"$TSSGAPIURL"\'\,," DbApp/src/environments/environment.ts
@@ -36,4 +39,24 @@ msg INFO "Build the frontend image & start container ...
 $( exec 2>&1
 docker-compose up -d --build frontend
 )"
+
+msg WAIT "Wait for frontend service to be healthy ...
+$( exec 2>&1
+maxTries=120
+try=0
+waitSecsToRetry=5
+until curl -Is "${TSSGAPPURL}" | grep -q '200 OK'
+do
+    sleep ${waitSecsToRetry}s
+    ((++try))
+    echo "    RETRY: Attempt ${try} ..."
+    if [ $try -gt $maxTries ] ; then
+        echo -e "\n"
+        echo "    ERROR: Frontend did not come up in $((try * waitSecsToRetry)) seconds. Exiting."
+        exit 1
+    fi
+done
+)" | grep -q ERROR && exit 1
+
+msg SUCCESS "Frontend can now be accessed at ${TSSGAPPURL}"
 msg END "... done."
